// <auto-generated />
using System;
using DotNet8BlazorWebAssembly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet8BlazorWebAssembly.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWasmDotNetShared.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publisher = "CD Project Red",
                            ReleaseYear = 2025,
                            Title = "Witcher 4"
                        },
                        new
                        {
                            Id = 2,
                            Publisher = "Blizzard",
                            ReleaseYear = 2027,
                            Title = "Diablo 5"
                        },
                        new
                        {
                            Id = 3,
                            Publisher = "Bethesda",
                            ReleaseYear = 2025,
                            Title = "Elder Scroll 6"
                        },
                        new
                        {
                            Id = 4,
                            Publisher = "대한소프트",
                            ReleaseYear = 2027,
                            Title = "씨뻘건 사막"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
